Update pt-pt Locale
lbphone/lb-phone-locales pull request #101
Opened 2024-04-10 21:22 UTC by BookmanPT

Portuguese language update to 7.1 LB-Phone version

2024-12-10 16:11 UTC, Maximus7474 commented
Hi @BookmanPT 

If your still up for it you can update your file with the new locale keys in the current [`en.json`](https://github.com/lbphone/lb-phone-locales/blob/main/en.json)

2024-12-10 16:12 UTC, Maximus7474 requested changes
Missing various keys and translations, please refer to the latest en.json file.

2024-12-10 22:38 UTC, BookmanPT commented
Im on it, give me a few days

2024-12-11 10:16 UTC, Maximus7474 approved these changes

2024-12-11 10:18 UTC, merged