Update it.json to 2.0.3
lbphone/lb-phone-locales pull request #112
Opened 2024-08-24 23:13 UTC by RealSly90

2024-10-05 22:33 UTC, Maximus7474 commented on it.json
>                  "PLACEHOLDER": "$1000",
Syntax error, remove the last `,` from `"$1000",`

2024-10-05 22:34 UTC, Maximus7474 commented on it.json
> +            "BACKUPS": "Backup",
Can be removed, duplicate entry with line 161.

2024-10-05 22:35 UTC, Maximus7474 requested changes
Thanks for your contribution !
Could you fix the two comments from my review ?

2024-10-07 22:26 UTC, RealSly90 commented
Done

2024-10-08 10:13 UTC, Maximus7474 commented
Thanks ! I will notify the devs

2024-12-09 23:10 UTC, Maximus7474 commented
Hey @fabioferrero90 

As your PR couldn't be merged previously, could you update your file with the newest en.json contents ?

2024-12-19 11:23 UTC, Maximus7474 commented
I will merge this PR, as part of an initiative of bringing all the locales up to date or as much as possible.

2024-12-19 11:23 UTC, merged