ba.json
lbphone/lb-phone-locales pull request #119
Opened 2024-10-29 12:25 UTC by 2blqck

I added a Bosnian translation and made minor changes to the English translation.

2024-12-09 22:14 UTC, Maximus7474 commented on ba.json
> +                "TITLE": "Error",
Added PIN_CODE_ERROR section, needs translating.

2024-12-09 22:15 UTC, Maximus7474 commented on ba.json
> +            "DONE_SUBTITLE": "You sent {amount} to {number}",
Missing translations on lines:
- 653, 654, 655
- 657, 658, 659, 660

2024-12-09 22:16 UTC, Maximus7474 commented on ba.json
> +            "LOCATION": "Location",
Added missing field LOCATION & CHOOSE_LOCATION, requires translation.

2024-12-09 22:16 UTC, Maximus7474 requested changes
Some missing translations have been added if you could update it.

2024-12-09 22:17 UTC, Maximus7474 commented
Hi @2blqck ,

Thanks for your contribution, I've left some comments if you could check them out

2024-12-10 08:53 UTC, 2blqck commented
I updated it, take a look now.

2024-12-10 11:24 UTC, Maximus7474 approved these changes

2024-12-10 11:25 UTC, Maximus7474 commented
Thanks for the update, really appreciated !

2024-12-10 11:25 UTC, merged